
#<font color="blue">Numerical Computation in Python - Numpy</font>



The numpy package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python.

To use numpy you need to import the module, using for example:

In [4]:
import numpy as np


## <font color="blue">Scalars and Vectors</font>


In the previous lessons we saw how _scalar_ values can be handled in python by simply writing an expession; for example the instruction:

In [2]:
heigth = 1.84

Concerning the vectorial quantities, the naive extension would be the use of lists. For example we can store in the valiable _l_ the list of integer numbers between 0 and 9: 

In [5]:
num_elements = 10

l = list(range(num_elements))
print(l, type(l))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>


Things are more complicated than that... In the **numpy package** the terminology used for vectors, matrices and higher-dimensional data sets is **array**. In the next cell, the numpy function _arange_ is used for the same purposes of the _range_ function, but it returns an _array_. In this specific case the _type()_ function returns _ndarray_ meaning that all the elements of the vector are of the same type which can be inspected by accessing to the field _dtype_ of the array: 

In [6]:
a = np.arange(num_elements)
print(a, type(a), a.dtype)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int64


# <font color="red">EXERCISE 1</font>

**Create a null vector of size 10 but the fifth value wich is 1 (hint: see `np.zeros`)**

In [54]:
#TO DO  

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**Why do we need to have a different type to handle vectorial data? Can't we just use lists?**

Yes we can! But there are 3 good reasons for not doing that:

1. Unneeded occupation of space
2. Computational Cost
3. Dedicated functions for linear algebra



### <font color="blue">1. Space requirements</font>


A list can contain potentially different types values for any element; this means that for every element in the list the information concerning the type must be stored somewhere in memory:

In [7]:
a = [1, 'hello', 24]
print(type(a), '\n')

for item in a:
    print(type(item))

<class 'list'> 

<class 'int'>
<class 'str'>
<class 'int'>


This is not required if we have a dedicated type for homogenuous data like numpy arrays...

### <font color="blue">2. Computational Cost</font>


Numpy array can use specific algorithms that, exploiting the fact that the contained values are of the same type, are faster. This fact can be checked empirically:

In [8]:
num_elements = 10**4
l = list(range(num_elements))
a = np.arange(num_elements)

In [9]:
%timeit sum(l)

10000 loops, best of 5: 78 µs per loop


In [11]:
%timeit a.sum()

The slowest run took 14.06 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 8.73 µs per loop


### <font color="blue">3. Dedicated Mathematical Functions</font>



#### <font color="blue">Operation Between scalars and vectors</font>


As long as two vectors have the same dimensions, the operations used for scalars can be generalized to vectors too. 

For example if we **add two vectors of the same length**, python will interpret it as "apply this operation elementwise":

In [13]:
birth = np.array([1954, 1936, 1982, 1994])
graduation = np.array([1979, 1965, 2007, 2018])
age_at_graduation = graduation - birth
age_at_graduation

#b = [1954, 1936, 1982, 1994]
#g = [1979, 1965, 2007, 2018]
#a = b - g
#a

array([25, 29, 25, 24])

What happens if we subtract a scalar to a vector?

In [14]:
2018 - birth

array([64, 82, 36, 24])

Again python will subtract the scalar from each element of the vector.. This is called __Automatic Broadcasting__

Similarly, the code in the next cell can be used to convert the result in months:

In [15]:
12 * (2018 - birth)

array([768, 984, 432, 288])

# <font color="red">EXERCISE 2</font>


**Create a 5x5 random matrix (use `np.random.randn()`)and normalize it between 0 and 1 (hint: see `np.min()` and `np.max()`; hint2: to normalize a vector or a matrix use the formula: $Znorm = \frac{Z - Zmin}{Zmax - Zmin}$)**

In [ ]:
#TO DO 

#### <font color="blue">Comparison Operators on arrays</font>



Comparison operators extend their behaviour to arrays too...

In [17]:
marriage = np.array([1981, 1963, 2008, 2018])
graduation < marriage

array([ True, False,  True, False])

Wait... But... How can we control if two arrays are equal?

In [ ]:
graduation == marriage

array([False, False, False,  True])

Numpy provides the function _all()_ exacly for this. This function returns _True_ if all the elements of the first array are equal to the corresponding elements of the second:

In [ ]:
np.all(graduation == marriage)

False

In [ ]:
np.all(graduation == graduation)

True

The package provides the function _any()_ which returns _True_ if at least one of the elements of the first array is equal to the corresponding element of the second:

In [ ]:
np.any(graduation != marriage)

True

It's possible to perform operation between list/tuples and arrays __if__ the dimensions match:

In [ ]:
marriage + [0, 0, 0, 0]

array([1981, 1963, 2008, 2018])

What happens is that behind the scenes the list or tuple will be converted to an array

Can we make operations between vectors of different length??

In [18]:
marriage + np.array([0, 0])

ValueError: ignored

# <font color="red">EXERCISE 3</font>


**Given the 1D array of values from 0 to 10 (inclusive), negate all elements which are between 3 and 8, in place.**


In [56]:
#TO DO 

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


# <font color="red">EXERCISE 4</font>

Create random vector of size 10 and replace the maximum value by 0 

In [ ]:
#TO DO




# <font color="red">EXERCISE 5</font>

Create a random 5x10 matrix and subtract the mean of each row. (hint: see the help for the `np.mean` function)

In [ ]:
#TO DO

## <font color="blue">Linear algebra operations</font>
 

**Vectorizing code **is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

Example: Dot Product between two vectors:

In [19]:
quantities = np.array([2, 5, 7, 1, 0, 3])
prices = np.array([5.99, 4.50, 9.99, 15, 2.50, 12])
quantities.dot(prices)

155.41000000000003

### Matrix Algebra

In [20]:
np.random.seed(1)
M = np.random.rand(3,3)
v = np.random.rand(3,1)

What about **matrix mutiplication**? There are two ways. We can either use the dot function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments:

In [21]:
#np.dot(M,M)
M*M

array([[1.73907352e-01, 5.18867376e-01, 1.30815988e-08],
       [9.14049845e-02, 2.15372915e-02, 8.52641608e-03],
       [3.46928663e-02, 1.19412216e-01, 1.57424429e-01]])

In [22]:
np.dot(M,v)

array([[0.52673288],
       [0.28769332],
       [0.51709009]])

In [23]:
np.dot(v.T,v)

array([[0.93557328]])

Alternatively, we can cast the array objects to the type matrix. This changes the behavior of the standard arithmetic operators +, -, * to use matrix algebra.

In [24]:
M1 = np.matrix(M)
v1 = np.matrix(v)

In [27]:
# Matrix - Matrix Product
M1 * M1

matrix([[0.39170621, 0.40614255, 0.06660683],
        [0.18764743, 0.27122344, 0.05022276],
        [0.25605086, 0.32198812, 0.18935432]])

In [28]:
# Matrix - Vector Product
M1 * v1

matrix([[0.52673288],
        [0.28769332],
        [0.51709009]])

In [29]:
# inner product
v1.T * v1

matrix([[0.93557328]])

In [ ]:
# with matrix objects, standard matrix algebra applies
v1 + M1*v1

matrix([[1.06554962],
        [0.70688783],
        [1.20230959]])

If we try to add, subtract or multiply objects with incomplatible shapes we get an error:

In [30]:
v = np.matrix([1,2,3,4,5,6]).T
np.shape(M), np.shape(v)

((3, 3), (6, 1))

In [31]:
M * v

ValueError: ignored

## <font color="blue">Manipulating Arrays</font>
 


### <font color="blue">Random Data</font>
 

In [ ]:
# uniform random numbers in [0,1]
np.random.rand(5,5)

In [ ]:
# standard normal distributed random numbers
np.random.randn(5,5)

### <font color="blue">Indexing</font>
  
We can index elements in an array using square brackets and indices:

In [32]:
np.random.seed(1)
M = np.random.rand(3,3)
v = np.random.rand(3,)

print(v)

# v is a vector, and has only one dimension, taking one index
v[0]

[0.53881673 0.41919451 0.6852195 ]


0.538816734003357

In [33]:
# M is a matrix, or a 2 dimensional array, taking two indices 
print(M)
M[1,1]

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]


0.14675589081711304

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array)

In [34]:
M[1]

array([0.30233257, 0.14675589, 0.09233859])

The same thing can be achieved with using : instead of an index:

In [35]:
M[1,:] # row 1

array([0.30233257, 0.14675589, 0.09233859])

In [36]:
M[:,1] # column 1

array([0.72032449, 0.14675589, 0.34556073])

We can assign new values to elements in an array using indexing:

In [37]:
M[0,0] = 1

In [ ]:
print(M)

[[1.00000000e+00 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]


In [38]:
# also works for rows and columns
M[1,:] = 0
M[:,2] = -1

In [39]:
print(M)

[[ 1.          0.72032449 -1.        ]
 [ 0.          0.         -1.        ]
 [ 0.18626021  0.34556073 -1.        ]]


## Index slicing

Index slicing is the technical name for the syntax M[lower:upper:step] to extract part of an array:


In [40]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [41]:
A[1:3]

array([2, 3])

Array slices are mutable: if they are assigned a new value the original array from which the slice was extracted is modified:

In [42]:
A[1:3] = [-2,-3]

A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in M[lower:upper:step]:

In [43]:
A[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [44]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [45]:
A[:3] # first three elements

array([ 1, -2, -3])

In [46]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the array (positive index from the begining):

In [47]:
A = np.array([1,2,3,4,5])

In [48]:
A[-1] # the last element in the array

5

Index slicing works exactly the same way for multidimensional arrays:

In [51]:
A = []
for m in range(5):
    A.append(np.array(list(range(5)))+[m*10]*5)
A = np.array(A)

print(A)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [52]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [53]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

## Fancy Indexing

Fancy indexing is the name for when an array or list is used in-place of an index:

In [ ]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [ ]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

array([11, 22, 34])

We can also use index masks: If the index mask is an Numpy array of data type bool, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element:

In [ ]:
B = np.array([n for n in range(5)])
B

array([0, 1, 2, 3, 4])

In [ ]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [ ]:
# same thing
row_mask = np.array([1,0,1,0,0], dtype=bool)
B[row_mask]

array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [ ]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
mask = (5 < x) * (x < 7.5)

mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [ ]:
x[mask]

array([5.5, 6. , 6.5, 7. ])